# Generated by Django 3.1.6 on 2021-02-12 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='order address')),
                ('amount', models.PositiveIntegerField(verbose_name='order amount')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='order date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completion date')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancel date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'canceled_at', 'completed_at', 'address', 'amount', 'is_completed', 'is_canceled'],
            },
        ),
    ]
