# Generated by Django 3.1.6 on 2021-02-22 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20210222_1651'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveOrder',
            fields=[
            ],
            options={
                'verbose_name': 'live order',
                'verbose_name_plural': 'live orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at', 'canceled_at', 'completed_at', 'address', 'amount', 'status'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
