# Generated by Django 3.1.6 on 2021-02-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210213_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpicture',
            options={'verbose_name': 'product picture', 'verbose_name_plural': 'product pictures'},
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='products.product'),
        ),
    ]
